---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
  
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: wordpress
type: Opaque
data:
  username: root
  password: asdf