---
- hosts: database
  roles:
    - postgresql-new
  pre_tasks:
    - name: enable firewalld service
      service:
        name: firewalld
        enabled: true
        state: started
    - name: enable firewalld port
      firewalld:
        port: "{{ postgres_http_port }}/tcp"
        state: enabled
        immediate: yes
        permanent: yes