---
- hosts: jenkins
  vars:
    jenkins_http_port: 80
  roles:
    - java
    - jenkins
  tasks:
    - name: enable firewalld port
      firewalld:
        port: "{{ jenkins_http_port }}/tcp"
        state: enabled
        immediate: yes
        permanent: yes
