---
- hosts: jenkins
  vars:
    jenkins_http_port: 8080
  roles:
    - java
    - jenkins
  tasks:
    - name: enable firewalld port
      firewalld:
        port: "{{ jenkins_http_port }}"
        state: enabled
        immediate: yes
        permanent: yes
