---
- hosts: k8s
  roles:
    #- docker
    - k8s-kubespray
  vars:
   docker_storage_setup: False
   docker_storage_type: disk
   docker_storage_device: /dev/sdb1 
   docker_storage_location: /data/docker
   selinux_reboot_required: True
   
  pre_tasks:
   - name: rm cobbler repo
     block:
      - name: rm cobbler repo
        command: rm -rf /etc/yum.repos.d/cobbler-config.repo
#        args:
#          creates: /dev/sdb1      
#      - name: Ensure Volume Group vg_docker Exist
#        lvg:
#         vg: "vg_docker"
#         pvs: "/dev/sdb1"
#     when: docker_storage_setup