- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the template and create vm "{{ vm_name }}"
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter }}"
      state: present
      folder: "{{ cluster_folder_name }}"
      template: "{{ vm_template }}"
      validate_certs: false
      name: "{{ vm_name }}"
      cluster: "{{ cluster_name }}"
      disk:
      - size_gb: "{{ vm_hdd_size_gb }}"
        type: thin
        datastore: datastore
      hardware:
        memory_mb: "{{ vm_ram_size_mb }}"
        num_cpus: "{{ vm_num_cpus }}"
        num_cpu_cores_per_socket: 2
        hotadd_cpu: true
        hotremove_cpu: true
        hotadd_memory: true
      wait_for_ip_address: true
      wait_for_ip_address_timeout: 600
      networks:
        - name: VM Network
          ip: "{{ vm_ip }}"
          netmask: 255.255.255.0
          start_connected: true
          type: static
          connected: true
          gateway: 10.10.10.1
      customization:
        dns_servers:
          - 10.10.10.11
          - 8.8.8.8
        dns_suffix:
          - paosin.local
  
    delegate_to: localhost
