---
- name: Deploying VMs to ESXI
  hosts: all
  connection: local
  gather_facts: no                                   
  roles:
    - role: vmware_vm_provisioning
      tags: vmware_vm_provisioning      
