nginx_vhosts:
  - listen: "80"
    server_name: "jenkins.paosin.local"
    return: "301 https://jenkins.paosin.local$request_uri"
    
  - listen: "443 ssl http2"
    server_name: "jenkins.paosin.local"
    server_name_redirect: "jenkins.paosin.local"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "jenkins.paosin.local.conf"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
      ssl_certificate     /DATA/ssl/jenkins.paosin.local.pem;
      ssl_certificate_key /DATA/ssl/jenkins.paosin.local.key;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;