certs:
 - jenkins.paosin.local.crt
 - jenkins.paosin.local.key

nginx_vhosts:
  - listen: "80"
    server_name: "jenkins.paosin.local"
    #server_name_redirect: "jenkins.paosin.local"
    return: "301 https://jenkins.paosin.local$request_uri"
    
  - listen: "443 ssl http2"
    server_name: "jenkins.paosin.local"
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "jenkins.paosin.local.conf"
    extra_parameters: |
      location / {
          proxy_set_header HOST $host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     
          proxy_pass http://127.0.0.1:8080;
      }

      ssl_certificate     /DATA/ssl/jenkins.paosin.local.crt;
      ssl_certificate_key /DATA/ssl/jenkins.paosin.local.key;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;