---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rwo
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.100.210
    # Exported path of your NFS server
    path: "/DATA/nfsshare"
