bind_listen_ipv4:
  - "127.0.0.1"
  - "10.10.10.11"

bind_allow_query:
  - "localhost"
  - "10.10.10.0/24"

 

dns_server: true  

bind_recursion: true

bind_zone_master_server_ip: 10.10.10.11
my_ip4_address: 10.10.10.11
acls:
  - name: acl1
    match_list:
      - 10.10.10.0/24
      - "10.10.10.11"
        
bind_zone_name_servers:
  - dns



#bind_zone_name: paosin.local
bind_zone_networks:
  - "10.10.10"

bind_zone_domains:    
  - name: k8s-cluster-001.local
    networks:
    - "10.10.12"
    hosts:
      - name: '@'
        ip: 10.10.10.11
      - name: '*.apps 300'
        ip: 10.10.10.41
        donotadd_reverse: true
      - name: dns
        ip: 10.10.10.11
    ### kube
      - name: '*'
        ip: 10.10.10.41
        donotadd_reverse: true
        
  - name: k8s-cluster-002.local
    networks:
    - "10.10.13"
    hosts:
      - name: '@'
        ip: 10.10.10.11
      - name: '*.apps 300'
        ip: 10.10.10.38
        donotadd_reverse: true
      - name: dns
        ip: 10.10.10.11
    ### kube
      - name: '*'
        ip: 10.10.10.38
        donotadd_reverse: true

  - name: k8s-istio-001.local
    networks:
    - "10.10.14"
    hosts:
      - name: '@'
        ip: 10.10.10.11
      - name: '*.apps 300'
        ip: 10.10.10.40
        donotadd_reverse: true
      - name: dns
        ip: 10.10.10.11
    ### kube
      - name: '*'
        ip: 10.10.10.40
        donotadd_reverse: true

  - name: k8s-istio-002.local
    networks:
    - "10.10.15"
    hosts:
      - name: '@'
        ip: 10.10.10.11
      - name: '*.apps 300'
        ip: 10.10.10.37
        donotadd_reverse: true
      - name: dns
        ip: 10.10.10.11
    ### kube
      - name: '*'
        ip: 10.10.10.37
        donotadd_reverse: true
                                                   
#  - name: kube.local
#    networks:
#    - "10.10.11"
#    hosts:
#      - name: '@'
#        ip: 10.10.10.11
#      - name: '*.apps 300'
#        ip: 10.10.10.40
#        donotadd_reverse: true
#      - name: masterdns
#        ip: 10.10.10.11
#    ### kube
#      - name: '*'
#        ip: 10.10.10.40
#        donotadd_reverse: true

  - name: paosin.local
    networks:
    - "10.10.10"
#    services:
#      - name: _etcd-server-ssl._tcp.ocp4-cluster-001
#        weight: 10
#        port: 2380
#        target: etcd-0.ocp4-cluster-001
#      - name: _etcd-server-ssl._tcp.ocp4-cluster-001
#        weight: 10
#        port: 2380
#        target: etcd-1.ocp4-cluster-001
#      - name: _etcd-server-ssl._tcp.ocp4-cluster-001
#        weight: 10
#        port: 2380
#        target: etcd-2.ocp4-cluster-001
    hosts:
      - name: '@'
        ip: 10.10.10.11
      - name: dns
        ip: 10.10.10.11
      - name: ldap
        ip: 10.10.10.12

      - name: vcenter
        ip: 10.10.10.6
      - name: awx
        ip: 10.10.10.22
      - name: harbor
        ip: 10.10.10.23 
      - name: gogs
        ip: 10.10.10.24
      - name: tanzu
        ip: 10.10.10.28
      - name: jenkins
        ip: 10.10.10.25

      - name: database
        ip: 10.10.10.27
      - name: k3s
        ip: 10.10.10.46
      - name: ocp-nfs
        ip: 10.10.10.55
      - name: quay
        ip: 10.10.10.66
      - name: plex
        ip: 10.10.10.101          
    ### Openshift
      - name: '*.apps 300'
        ip: 10.10.10.80
        donotadd_reverse: true
               
      - name: ocp-infra1
        ip: 10.10.10.80
        
      - name: openshift
        ip: 10.10.10.81
    
      - name: openshift-int
        ip: 10.10.10.81
            
      - name: ocp-master1
        ip: 10.10.10.81  
        
        
      - name: ocp-node1
        ip: 10.10.10.83
        
      - name: ocp-node2
        ip: 10.10.10.84
        
      - name: ocp-node3
        ip: 10.10.10.85
       
   
                

        
      - name: '*.apps.argocd 300'
        ip: 10.10.10.221
        donotadd_reverse: true


      - name: '*.apps.dev 300'
        ip: 10.10.10.45
        donotadd_reverse: true
################ OCP4  ################ 
      - name: '*.apps.ocp4-c01 300'
        ip: 10.10.10.30
        donotadd_reverse: true
        
      - name: api.ocp4-c01
        ip: 10.10.10.30  
        
      - name: api-int.ocp4-c01
        ip: 10.10.10.30   
    
      - name: bastion
        ip: 10.10.10.30
        
      #- name: bastion.rnd
      #  ip: 10.10.10.30
        
      - name: bootstrap.rnd
        ip: 10.10.10.29
        
      - name: master1.rnd
        ip: 10.10.10.31
        
      - name: infra1.rnd
        ip: 10.10.10.32
               
      - name: worker1.rnd
        ip: 10.10.10.33
        
      - name: worker2.rnd
        ip: 10.10.10.34
        
      - name: worker3.rnd
        ip: 10.10.10.35
        
      - name: ocs01.rnd
        ip: 10.10.10.36
        
      - name: ocs02.rnd
        ip: 10.10.10.37
        
      - name: ocs03.rnd
        ip: 10.10.10.38
                
################ OKD4  ################ 
      - name: '*.apps.okd4-c01 300'
        ip: 10.10.10.78
        donotadd_reverse: true
      - name: api.okd4-c01
        ip: 10.10.10.79
      - name: api-int.okd4-c01
        ip: 10.10.10.79            
                           
gateway: 10.10.10.1
vlan_id: 1
domain: "paosin.local"
prefix_length: 24
interface_label: "VM Network"


