bind_listen_ipv4:
  - "127.0.0.1"
  - "10.10.10.11"

bind_allow_query:
  - "localhost"
  - "10.10.10.0/24"

  
dns_server: true  

bind_recursion: true

bind_zone_master_server_ip: 10.10.10.11
my_ip4_address: 10.10.10.11
acls:
  - name: acl1
    match_list:
      - 10.10.10.0/24
      - "10.10.10.11"
        
bind_zone_name_servers:
  - masterdns



#bind_zone_name: paosin.local
bind_zone_networks:
  - "10.10.10"

bind_zone_domains:
  - name: ocp.local
    networks:
    - "10.10.12"
    services:
      - name: _etcd-server-ssl._tcp.ocp4-cluster-001
        weight: 10
        port: 2380
        target: etcd-0.ocp4-cluster-001.ocp.local
      - name: _etcd-server-ssl._tcp.ocp4-cluster-001
        weight: 10
        port: 2380
        target: etcd-1.ocp4-cluster-001.ocp.local
      - name: _etcd-server-ssl._tcp.ocp4-cluster-001
        weight: 10
        port: 2380
        target: etcd-2.ocp4-cluster-001.ocp.local
    hosts:
#      - name: '@'
#        ip: 10.10.10.11
    ### Openshift4
      - name: '*.apps.ocp4-cluster-001 300'
        ip: 10.10.10.58
        donotadd_reverse: true
#      - name: '*'
#        ip: 10.10.10.58
#        donotadd_reverse: true
      - name: api.ocp4-cluster-001
        ip: 10.10.10.58           
      - name: api-int.ocp4-cluster-001
        ip: 10.10.10.58                  
      - name: lb.ocp4-cluster-001
        ip: 10.10.10.58
        
      - name: control-plane-0.ocp4-cluster-001
        ip: 10.10.10.60 
      - name: control-plane-1.ocp4-cluster-001
        ip: 10.10.10.61 
      - name: control-plane-2.ocp4-cluster-001
        ip: 10.10.10.62 
        
      - name: bootstrap.ocp4-cluster-001
        ip: 10.10.10.59
        
      - name: etcd-0.ocp4-cluster-001
        ip: 10.10.10.60 
      - name: etcd-1.ocp4-cluster-001
        ip: 10.10.10.61 
      - name: etcd-2.ocp4-cluster-001
        ip: 10.10.10.62 
        
      - name: compute-0.ocp4-cluster-001
        ip: 10.10.10.63
      - name: compute-1.ocp4-cluster-001
        ip: 10.10.10.64 
      - name: masterdns
        ip: 10.10.10.11
                                    
  - name: kube.local
    networks:
    - "10.10.11"
    hosts:
#      - name: '@'
#        ip: 10.10.10.11
      - name: '*.apps 300'
        ip: 10.10.10.40
        donotadd_reverse: true
      - name: masterdns
        ip: 10.10.10.11
    ### kube
#      - name: '*'
#        ip: 10.10.10.40
#        donotadd_reverse: true

  - name: paosin.local
    networks:
    - "10.10.10"
    services:
      - name: _etcd-server-ssl._tcp.ocp-v4
        weight: 10
        port: 2380
        target: etcd-0.ocp4.paosin.local
      - name: _etcd-server-ssl._tcp.ocp-v4
        weight: 10
        port: 2380
        target: etcd-1.ocp4.paosin.local
      - name: _etcd-server-ssl._tcp.ocp-v4
        weight: 10
        port: 2380
        target: etcd-2.ocp4.paosin.local
    hosts:
      - name: '@'
        ip: 10.10.10.11
      - name: masterdns
        ip: 10.10.10.11
      - name: vcenter
        ip: 10.10.10.6
      - name: awx-ansible
        ip: 10.10.10.22
      - name: harbor
        ip: 10.10.10.23 
      - name: gogs
        ip: 10.10.10.24
      - name: postgresql
        ip: 10.10.10.27
      - name: jenkins
        ip: 10.10.10.25
      - name: k8s-master1
        ip: 10.10.10.30
      - name: k8s-node1
        ip: 10.10.10.32
      - name: k8s-node2
        ip: 10.10.10.33
      - name: k8s-node3
        ip: 10.10.10.34
      - name: ocp-nfs
        ip: 10.10.10.55
      - name: emby
        ip: 10.10.10.102
      - name: plex
        ip: 10.10.10.101          
    ### Openshift
      - name: '*.apps 300'
        ip: 10.10.10.80
        donotadd_reverse: true
#      - name: '*.kube.paosin.local 300'
#        ip: 10.10.10.40
#        donotadd_reverse: true
    ### Openshift
#      - name: '*'
#        ip: 10.10.10.80
#        donotadd_reverse: true
               
      - name: ocp-infra1
        ip: 10.10.10.80
        
      - name: openshift
        ip: 10.10.10.81
    
      - name: openshift-int
        ip: 10.10.10.81
            
      - name: ocp-master1
        ip: 10.10.10.81  
        
        
      - name: ocp-node1
        ip: 10.10.10.71
        
      - name: ocp-node2
        ip: 10.10.10.72
        
      - name: ocp-node3
        ip: 10.10.10.73
       
      - name: ocp-glusterfs1
        ip: 10.10.10.76
      - name: ocp-glusterfs2
        ip: 10.10.10.77 
      - name: ocp-glusterfs3
        ip: 10.10.10.78 
   ### K8s domain     
      - name: '*.apps.k8s 300'
        ip: 10.10.10.40
        donotadd_reverse: true
    ### Openshift4
      - name: '*.apps.ocp-v4 300'
        ip: 10.10.10.58
        donotadd_reverse: true
#      - name: '*'
#        ip: 10.10.10.58
#        donotadd_reverse: true
      - name: api.ocp-v4
        ip: 10.10.10.58           
      - name: api-int.ocp-v4
        ip: 10.10.10.58                  
      - name: lb.ocp4-v4
        ip: 10.10.10.58
        
      - name: control-plane-0.ocp-v4
        ip: 10.10.10.60 
      - name: control-plane-1.ocp-v4
        ip: 10.10.10.61 
      - name: control-plane-2.ocp-v4
        ip: 10.10.10.62 
        
      - name: bootstrap.ocp-v4
        ip: 10.10.10.59
        
      - name: etcd-0.ocp-v4
        ip: 10.10.10.60 
      - name: etcd-1.ocp-v4
        ip: 10.10.10.61 
      - name: etcd-2.ocp-v4
        ip: 10.10.10.62 
        
      - name: compute-0.ocp-v4
        ip: 10.10.10.63
      - name: compute-1.ocp-v4
        ip: 10.10.10.64 
                           
gateway: 10.10.10.1
vlan_id: 1
domain: "paosin.local"
prefix_length: 24
interface_label: "VM Network"


