postgresql_version: 11
postgresql_conf:
   - listen_addresses: "'*'"    # disable network listening (listen on unix socket only)
   - max_connections: 50       # decrease connection limit
   
   
postgres_http_port: 5432

postgresql_pg_hba_conf:
 - local all postgres    trust
 - local all all    trust
 - host all all 127.0.0.1/32   trust
 - host all all ::1/128   trust
 - host all all 0.0.0.0/0   md5
