---
- name: Install EPEL repo.
  yum:
    name: epel-release
    state: present

- name:  origin.repo
  shell: "cd /etc/yum.repos.d && curl -O https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo"
  args:
   executable: /bin/bash



   
- name:  yum clean all
  shell: yum clean all
  args:
   executable: /bin/bash
   
- name: installing yum apps
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - NetworkManager
    - docker
    - bash-completion
    - vim
    - tree
    - wget 
    - git 
    - net-tools 
    - bind-utils 
    - python-rhsm-certificates 
    - ansible
    - glusterfs-client
    - psacct
    - yum-utils 
    - iptables-services 
    - bash-completion 
    - kexec-tools 
    - sos
    - pyOpenSSL

- name:  disable epel repo
  shell: "sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo"
  args:
   executable: /bin/bash
   
   
- include: masters.yml
  when: openshift_origin_node_type == "master"
  
#- include: infranodes.yml
#  when: openshift_origin_node_type == "infranode"
  
#- include: nodes.yml  
#  when: openshift_origin_node_type is defined
  
#- include: lab.yml  
#  when: openshift_origin_node_type == "lab"
   