---
- name: Install EPEL repo.
  yum:
    name: epel-release
    state: present

#- name:  origin.repo
#  shell: "cd /etc/yum.repos.d && curl -O https://storage.googleapis.com/origin-ci-test/releases/openshift/origin/master/origin.repo"
#  args:
#   executable: /bin/bash
- selinux:
    policy: targeted
    state: enforcing
    
- name:  yum clean all
  shell: yum clean all
  args:
   executable: /bin/bash
   
- name: installing yum apps
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - NetworkManager
    - docker
    - bash-completion
    - vim
    - tree
    - wget
    - git
    - net-tools 
    - bind-utils 
    - python-rhsm-certificates 
    - ansible
    - glusterfs-client
    - psacct
    - yum-utils 
    - iptables-services 
    - bash-completion 
    - kexec-tools 
    - sos
    - python-pip
    #- pyOpenSSL

- pip:
    name: pyopenssl
    
- name: Copy certificates
  copy: src=certs dest=/root/

- name: enable and start NetworkManager 
  service: name=NetworkManager state=started  enabled=yes

- name: shutdown
  command: /sbin/shutdown -h now 
  when: shutdown is defined
   
- include: masters.yml
  when: openshift_origin_node_type == "master"


- name:  disable epel repo
  shell: "sed -i -e 's/^enabled=1/enabled=0/' /etc/yum.repos.d/epel.repo"
  args:
   executable: /bin/bash
     
- name: remove docker
  yum: name={{ item }} state=absent
  ##when: docker_storage_setup == "true"
  with_items:
    - docker

#- name: stop docker 
#  service: name=docker state=stopped 
#  #when: docker_storage_setup == "true"   

- name: unmount docker stuff
  mount:
    path: /var/lib/docker/containers
    state: absent
  #when: docker_storage_setup == "true"
    
- name:  remove /var/lib/docker/
  shell: rm -rf /var/lib/docker
  args:
   executable: /bin/bash
  #when: docker_storage_setup == "true"
  

- name: install docker
  yum: name={{ item }} state=present
  #when: docker_storage_setup == "true"
  with_items:
    - docker

- name: "Create Docker Storage Daemon"
  copy:
    src=docker/docker-storage-setup
    dest=/etc/sysconfig/docker-storage-setup 
  ignore_errors: yes 
  
  
#- name: "Create Docker Storage File"
#  copy:
#    src=docker/daemon.json
#    dest=/etc/docker/daemon.json
#  ignore_errors: yes 
    
- name:  Configuring Docker Storage
  shell: docker-storage-setup
  args:
   executable: /bin/bash
  #when: docker_storage_setup == "true"
  ignore_errors: yes

#- name:  Configuring Docker Storage
#  shell: "sed -i 's/selinux-enabled/selinux-enabled\ --insecure-registry\ 172.50.0.0\/16/g' /etc/sysconfig/docker"
#  args:
#   executable: /bin/bash
#  #when: docker_storage_setup == "true"
  

   
- name: enable and start docker 
  service: name=docker state=started  enabled=yes 
  
#- include: nodes.yml  
#  when: openshift_origin_node_type is defined
  
#- include: lab.yml  
#  when: openshift_origin_node_type == "lab"
   