- name: clone a openshift repository
  git: >
    repo=https://github.com/openshift/openshift-ansible
    dest=/opt/openshift-ansible
    version=release-3.9
    
- name: add openshift-ansible hosts
  copy: >
    src=files/inventory/hosts
    dest=/opt/openshift-ansible/inventory/hosts
    owner=root
    group=root
    mode=0600
    
- name: install ansible and Heketi utilities
  yum: name={{ item }} state=present
  with_items:
    - heketi-client
    - heketi-templates
    - heketi
    - python-heketi
    - python2-passlib
    - java-1.8.0-openjdk-headless

- name: copy private key
  copy: src=heketi/insecure_private_key owner=heketi group=heketi dest=/etc/heketi/insecure_private_key force=yes mode=600

- name: copy heketi configuration
  copy: src=heketi/heketi.json owner=root group=root dest=/etc/heketi/heketi.json force=yes mode=644

- name: copy topology configuration
  copy: src=heketi/topology.json owner=root group=root dest=/etc/heketi/topology.json force=yes mode=644

- name: start heketi service 
  service: name=heketi state=started enabled=yes
    
#heketi-cli --server http://10.10.10.70:8080  topology load  --json=/etc/heketi/topology.json
    
