- name: install docker
  yum: name={{ item }} state=present
  enablerepo: epel
  with_items:
    - docker

- name: stop docker 
  service: name=docker state=stopped 
  when: format_hdd is defined   

- name:  remove /var/lib/docker/
  shell: rm -rf /var/lib/docker
  args:
   executable: /bin/bash
  when: docker_storage_setup is defined
  
- name: "Create Docker Storage File"
  copy:
    src=docker-storage-setup
    dest=/etc/sysconfig/docker-storage-setup 
  ignore_errors: yes 
    
- name:  Configuring Docker Storage
  shell: docker-storage-setup
  args:
   executable: /bin/bash
  when: docker_storage_setup is defined
  ignore_errors: yes

#- name:  Configuring Docker Storage
#  shell: "sed -i 's/selinux-enabled/selinux-enabled\ --insecure-registry\ 172.50.0.0\/16/g' /etc/sysconfig/docker"
#  args:
#   executable: /bin/bash
#  when: format_hdd is defined
  

   
- name: enable and start docker 
  service: name=docker state=started  enabled=yes 