- name: remove docker
  yum: name={{ item }} state=absent
  when: docker_storage_setup == "true"
  with_items:
    - docker

#- name: stop docker 
#  service: name=docker state=stopped 
#  when: docker_storage_setup == "true"   

- name: unmount docker stuff
  mount:
    path: /var/lib/docker/containers
    state: absent
  when: docker_storage_setup == "true"
    
- name:  remove /var/lib/docker/
  shell: rm -rf /var/lib/docker
  args:
   executable: /bin/bash
  when: docker_storage_setup == "true"
  

- name: install docker
  yum: name={{ item }} state=present
  when: docker_storage_setup == "true"
  with_items:
    - docker

- name: "Create Docker Storage Daemon"
  copy:
    src=docker/docker-storage-setup
    dest=/etc/sysconfig/docker-storage-setup 
  ignore_errors: yes 
  
  
#- name: "Create Docker Storage File"
#  copy:
#    src=docker/daemon.json
#    dest=/etc/docker/daemon.json
#  ignore_errors: yes 
    
- name:  Configuring Docker Storage
  shell: docker-storage-setup
  args:
   executable: /bin/bash
  when: docker_storage_setup == "true"
  ignore_errors: yes

#- name:  Configuring Docker Storage
#  shell: "sed -i 's/selinux-enabled/selinux-enabled\ --insecure-registry\ 172.50.0.0\/16/g' /etc/sysconfig/docker"
#  args:
#   executable: /bin/bash
#  when: docker_storage_setup == "true"
  

   
- name: enable and start docker 
  service: name=docker state=started  enabled=yes 