apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: primary-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi

