
- name: Add Docker CE repository
  shell: yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo 

- name: Install Docker
  yum: 
   name: docker
   state: absent


- name: yum install packages for k8s
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - yum-utils 
    - device-mapper-persistent-data 
    - lvm2
    - docker-ce-18.09.8-3.el7.x86_64
    - container-storage-setup
  ignore_errors: True


      
- name: "Create Docker Storage Daemon"
  copy:
    src: docker/docker-storage-setup
    dest: /etc/sysconfig/docker-storage-setup
    
- name:  Run Docker Storage Setup
  command:  /usr/bin/container-storage-setup
 # ignore_errors: yes

- name: "Create Docker Storage Daemon"
  copy:
    src: docker/daemon.json
    dest: /etc/docker/daemon.json
      
- name: enable and start docker 
  service: 
   name: docker 
   state: started  
   enabled: yes  