apiVersion: v1
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.10.10.40-10.10.10.42
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system

